### ISSUE TITLE
Slicing in Cura - Unable to slice

### ISSUE THREAD

**Issue by Conzar** [Howchoo/random-bits#1]
I have followed [your guide](https://howchoo.com/g/mjbmmgmxymn/using-cura-with-the-geeetech-e180-mini-3d-printer) and am attempting to slice in cura the [better spool holder](https://www.homofaciens.de/technics-machines-3D-printer-Geeetech-E180_en.htm).

I get an error stating the model doesn't fit.  I have taken screenshots of the settings.  Can you take a look?  I am thinking there must be a configuration issue with my cura: https://imgur.com/a/0rv3D

Thank you

**Comment by ZLevine** [comment]
I didn't bother printing the handle (just the spool and AC adapter holder); I actually printed these with my Anet A8. Nonetheless, it should fit as the model creator posted a photo of it being printed on the E180.

Are you sure it's scaled 100%? If so, try scaling it down a bit, attempt a print, and see if it fits. It's possible the STL itself is scaled up for some reason.

**Comment by Conzar** [comment]
Thank you for responding @ZLevine 

The print area is 130cmx130cm so should fit as the handle is 125cmx120cm.  The guy that made these printed them on his E180 so it does fit.  I think the problem is in the configuration.  I am new to cura so am thinking maybe its the print profile, material, or printer settings.  

Here is the image of the handle with both translation and scaling tools.
https://imgur.com/a/6Fh1m

**Comment by Conzar** [comment]
It was the build plate adhesion setting.  I turned it off and its ready to slice!
https://imgur.com/wskHLyW
